import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";  // ✅ Tailwind가 적용된 글로벌 CSS 가져오기
import Navigation from "./component/Navigation";
import SideNavigation from "./component/sideNavigation";
import Footer from "./component/footer";
import React from 'react';
import FontAwesomeConfig from "./fontawesome";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata = {
  title: "Next js",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {


  console.log('RootLayout 재렌더링');
  return (
    <html>
      <head>
        <FontAwesomeConfig></FontAwesomeConfig>
      </head>
      <body className="bg-gray-100"> {/* Ensure body has Tailwind classes if needed */}
        <Navigation></Navigation>
        
        <main>
          <div className="flex">
          <SideNavigation></SideNavigation>
          {children}
          </div>
        
        </main>
       
      </body>
    </html>
  );
}

export const dynamic = "force-dynamic";